sonar.projectKey=andreaccamachoj_marketplace-cafe-front
sonar.organization=andreaccamachoj

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/coverage/**

# ESTA es la línea crítica para coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info
